# Generated by Django 5.0.4 on 2024-04-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maximumvalue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='minimumvalue',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
